Losson10 try1
grigorii-ch/BlankProject pull request #15
Opened 2021-04-29 16:27 UTC by grigorii-ch

2021-04-29 17:57 UTC, tlt-java-courses requested changes

2021-04-29 17:57 UTC, tlt-java-courses commented on src/main/resources/sausages.txt
> +Сервелад:2:1
Пример файла я прикладывал к ДЗ

2021-04-29 17:57 UTC, tlt-java-courses commented on src/main/java/com/chuprynin/epam/rd/task1/TaskOne.java
> +            writeToFileStream(stringListUUID);
Форматирование кода

2021-04-29 17:57 UTC, tlt-java-courses commented on src/main/java/com/chuprynin/epam/rd/task1/TaskOne.java
> +
Перенос тут есть, а в остальных методах нет

2021-04-29 17:57 UTC, tlt-java-courses commented on src/main/java/com/chuprynin/epam/rd/task2/TaskTwo.java
> +        List<Sausage> sausages = hepler.getNewList();;
2 ;;

2021-04-29 17:57 UTC, tlt-java-courses commented on src/main/java/com/chuprynin/epam/rd/task2/TaskTwo.java
> +        return stringList.stream().map(hepler::convertToPojo).collect(Collectors.toList());
По клинкоду если цепочки вызовов методов с переносами на следующую строку

2021-04-29 17:57 UTC, tlt-java-courses commented on src/main/java/com/chuprynin/epam/rd/task2/pojo/Sausage.java
> +public class Sausage {
Давай использовать lombok

2021-04-29 17:57 UTC, tlt-java-courses commented on src/main/resources/logback.xml
> +    <logger name="com.chuprynin.epam.rd.task2.TaskTwo" level="debug" additivity="false">
А для чего нам одинаковые аппендеры на все классы, давай один сделаем на весь проект

2021-04-30 12:34 UTC, grigorii-ch commented on src/main/java/com/chuprynin/epam/rd/task2/TaskTwo.java
> +        List<Sausage> sausages = hepler.getNewList();;
Убрал лишний символ ;

2021-04-30 12:59 UTC, grigorii-ch commented on src/main/java/com/chuprynin/epam/rd/task1/TaskOne.java
> +
Убрал

2021-04-30 12:59 UTC, grigorii-ch commented on src/main/java/com/chuprynin/epam/rd/task1/TaskOne.java
> +            writeToFileStream(stringListUUID);
Исправил

2021-04-30 13:11 UTC, grigorii-ch commented on src/main/java/com/chuprynin/epam/rd/task2/TaskTwo.java
> +        return stringList.stream().map(hepler::convertToPojo).collect(Collectors.toList());
Добавил переносы.

2021-04-30 14:17 UTC, grigorii-ch commented on src/main/resources/sausages.txt
> +Сервелад:2:1
Переделал на приложенный файл, с декодированием из Base64

2021-04-30 14:54 UTC, grigorii-ch commented on src/main/resources/logback.xml
> +    <logger name="com.chuprynin.epam.rd.task2.TaskTwo" level="debug" additivity="false">
Исправил на один аппендер.

2021-04-30 15:20 UTC, grigorii-ch commented on src/main/java/com/chuprynin/epam/rd/task2/pojo/Sausage.java
> +public class Sausage {
Добавил @Data

2021-05-01 17:47 UTC, tlt-java-courses requested changes

2021-05-01 17:47 UTC, tlt-java-courses commented on src/main/java/com/chuprynin/epam/rd/task2/pojo/Sausage.java
> +    public Sausage(String type, int weight, long cost) {
Может воспользуемся lombok для генерации конструктора?

2021-05-01 17:47 UTC, tlt-java-courses commented on src/main/java/com/chuprynin/epam/rd/task2/pojo/Sausage.java
> +    public String toString() {
У тебя уже навешана @Data, для чего дублирование?

2021-05-01 17:47 UTC, tlt-java-courses commented on src/main/java/com/chuprynin/epam/rd/Main.java
> +        log.debug(taskOneResult.toString());
В логах желательно чтобы был текст описывающий происходящее

2021-05-01 18:38 UTC, grigorii-ch commented on src/main/java/com/chuprynin/epam/rd/task2/pojo/Sausage.java
> +    public Sausage(String type, int weight, long cost) {
Добавил аннотации

2021-05-01 18:38 UTC, grigorii-ch commented on src/main/java/com/chuprynin/epam/rd/task2/pojo/Sausage.java
> +    public String toString() {
Убрал toString

2021-05-01 18:43 UTC, grigorii-ch commented on src/main/java/com/chuprynin/epam/rd/Main.java
> +        log.debug(taskOneResult.toString());
Вынес логирование в Main + добавил логи для такски 3

2021-05-02 20:10 UTC, tlt-java-courses approved these changes

2021-05-02 20:10 UTC, tlt-java-courses commented on src/main/java/com/chuprynin/epam/rd/helpers/TasksHepler.java
> +public class TasksHepler {
JavaDoc перед аннотациями

2021-05-02 20:10 UTC, tlt-java-courses commented on src/main/java/com/chuprynin/epam/rd/task3/FileSystemProvider.java
> +    private String treePatch = "\n";
По ДЗ нужно Объектное представление, а не строку

2021-05-02 20:10 UTC, tlt-java-courses commented on src/main/java/com/chuprynin/epam/rd/task2/TaskTwo.java
> +    TasksHepler hepler = new TasksHepler();
private

2021-05-02 20:10 UTC, tlt-java-courses commented on src/main/java/com/chuprynin/epam/rd/Main.java
> +        fileSystemProvider.run("src/main",0);
`src/main` можно в константу вынести

2021-05-02 20:10 UTC, tlt-java-courses commented on src/main/java/com/chuprynin/epam/rd/task2/TaskTwo.java
> +    private final static String PATCH_FILE = "src/main/resources/File.txt";
Если в jar собрать и исполнить, оно считается?

2021-05-02 20:10 UTC, merged