Task1
grigorii-ch/BlankProject pull request #19
Opened 2021-05-19 13:01 UTC by grigorii-ch

added:
  - depends postgresql and liquibase to root pom.xml
  - liquibase-maven-plugin to db module pom.xml
  - init.sql
  - database_example_changelog.xml (changeSet)

2021-05-19 18:24 UTC, tlt-java-courses requested changes

2021-05-19 18:24 UTC, tlt-java-courses commented on blank-project-db/pom.xml
> +    <properties>
В мавене проперти идут до зависимостей

2021-05-19 18:24 UTC, tlt-java-courses commented on blank-project-db/pom.xml
> +        <db.host>localhost</db.host>
Это проверти для liquibase а не db. Давай переименуем

2021-05-19 18:24 UTC, tlt-java-courses commented on blank-project-db/src/main/resources/db/database_example_changelog.xml
> +<?xml version="1.0" encoding="UTF-8" ?>
Давай назовем данный класс не с `example` а названием твоего проекта

2021-05-19 18:24 UTC, tlt-java-courses commented on blank-project-db/src/main/resources/db/database_example_changelog.xml
> +<databaseChangeLog
Давай сделаем этот ченжлог комулятивным, т.к. он будет сбором с инклюдами других ченжлогов

2021-05-19 18:24 UTC, tlt-java-courses commented on blank-project-db/src/main/resources/db/database_example_changelog.xml
> +    <changeSet id="1" author="Grigoriy">
1. Давай id назовем как-то более говоряще, хотя бы дату с описанием происходящего.
2. Давай запишем в авторстве Имя_Фамилию 
3. Если у тебя будет ошибка в создании одной из таблиц, откатятся все изменения в рамках скрипта миграции. Давай разделим 1 большой на много маленьких, хотя бы 1 скрипт миграции на одну таблицу

2021-05-19 18:24 UTC, tlt-java-courses commented on pom.xml
> -                                            <minimum>0.7</minimum>
Зачем?

2021-05-19 18:24 UTC, tlt-java-courses commented on blank-project-db/src/main/resources/init.sql
> +drop schema if exists chuprynin;
Не придирка, и сам не понимаю, но многие ратуют что ключевае слова должны быть в UPPER_CASE

2021-05-20 11:38 UTC, grigorii-ch commented on blank-project-db/pom.xml
> +    <properties>
Поправил

2021-05-20 11:48 UTC, grigorii-ch commented on blank-project-db/pom.xml
> +        <db.host>localhost</db.host>
Поправил

2021-05-20 11:51 UTC, grigorii-ch commented on blank-project-db/src/main/resources/db/database_example_changelog.xml
> +<?xml version="1.0" encoding="UTF-8" ?>
Инзменил на database_blankproject_changelog.xml

2021-05-20 17:53 UTC, grigorii-ch commented on blank-project-db/src/main/resources/db/database_example_changelog.xml
> +<databaseChangeLog
Разложил по разным ченжлогам

2021-05-20 18:12 UTC, grigorii-ch commented on blank-project-db/src/main/resources/db/database_example_changelog.xml
> +    <changeSet id="1" author="Grigoriy">
Изменил id
добавил  Имя_Фамилию
раскидал по разным ченжлогам +  добавил preConditions на проверку существования таблицы с таким именем

2021-05-20 18:14 UTC, grigorii-ch commented on pom.xml
> -                                            <minimum>0.7</minimum>
Вернул, не помню зачем менял :)

2021-05-20 18:18 UTC, grigorii-ch commented on blank-project-db/src/main/resources/init.sql
> +drop schema if exists chuprynin;
Перевел в UPPER_CASE

2021-05-21 17:58 UTC, tlt-java-courses requested changes

2021-05-21 17:58 UTC, tlt-java-courses commented on blank-project-db/src/main/resources/db/database.changelog.v1.customer.xml
> +<databaseChangeLog
Зачем столько ченжлогов? Давай сделаем папку с названием условно v1 и туда сложим ещё один ченжлог, который будет иметь версию v1.0 и содержать в себе перечень ченжсетов

2021-05-23 03:11 UTC, grigorii-ch commented on blank-project-db/src/main/resources/db/database.changelog.v1.customer.xml
> +<databaseChangeLog
Не уверен что правильно понял,
Добавил папку v1 туда вынес подкорневой ченджлог и в него списал остальные, ну и + имена им покороче сделал

2021-05-23 05:54 UTC, closed without merging